### ISSUE TITLE
Status: Failed to Create

### ISSUE THREAD

**Issue by YeolJ00** [gui549/Look-Out-Your-Windows#2]
### Problem Overview

I cannot run the .exe file to create images.
After choosing the images (up to step 4 in Getting Started section) and hitting "OK",
nothing happens and "Status: Failed to create" appears at the bottom of the window.

I tested on various images from the internet, with different resolutions (700x700 ~ 5000x4000) and different DPI/
All the images I tested were 8bit images in jpg format.

I ran the .exe file on a windows10 desktop.
Since the file seems to be written in python, I have python3.7 installed with anaconda

P.S The window size isn't adaptive so I only get a low resolution preview of my selected image.

**Comment by gui549** [comment]
The preview image is to make sure that you've chosen the right image, 
so I guess that the high-resolution preview is not required. 
Do you think a high-resolution is needed?

I found some bugs and fixed them. 
Would you download the latest version and try again?

**Comment by YeolJ00** [comment]
Release 0.0.3 solved the issue.
thx!
